apiVersion: apps/v1
kind: Deployment
metadata:
  name: placement-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: placement-portal
  template:
    metadata:
      labels:
        app: placement-portal
    spec:
      containers:
      - name: placement-portal
        image: 24mis0545/placement-portal:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: placement-portal-service
spec:
  type: NodePort
  selector:
    app: placement-portal
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
